version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - app
    environment:
      - REDIS_REPLICATION_MODE=master
    command: ['redis-server', '--bind', 'redis', '--port', '6379']

  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    networks:
      - app
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news

networks:
  app:
    name: trnr-network
